## Step 1: IMPORT OF LIBRARIES

In [145]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

## Step 2: LOAD OF DATA

In [146]:
matches = pd.read_csv("../data/raw_data/ipl_matches_data.csv", encoding="latin1")
deliveries = pd.read_csv("../data/raw_data/ball_by_ball_data.csv", encoding="latin1")
players = pd.read_csv("../data/raw_data/players-data-updated.csv", encoding="latin1")
teams = pd.read_csv("../data/raw_data/teams_data.csv", encoding="latin1")

## Step 3: INITIAL INFORMATION

In [147]:
print(matches.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   match_id         1169 non-null   int64
 1   season_id        1169 non-null   int64
 2   balls_per_over   1169 non-null   int64
 3   city             1118 non-null   object
 4   match_date       1169 non-null   object
 5   event_name       1169 non-null   object
 6   match_number     1099 non-null   float64
 7   gender           1169 non-null   object
 8   match_type       1169 non-null   object
 9   format           1169 non-null   object
 10  overs            1169 non-null   int64
 11  season           1169 non-null   object
 12  team_type        1169 non-null   object
 13  venue            1169 non-null   object
 14  toss_winner      1168 non-null   object
 15  team1            1169 non-null   object
 16  team2            1169 non-null   object
 17  toss_decision    1168 non-null   object
 18  match_winner     1161 non-null   object
 19  win_by_runs      531 non-null    float64
 20  win_by_wickets   615 non-null    float64
 21  player_of_match  1161 non-null   float64
 22  result           1169 non-null   object
 23  stage            4 non-null      object
dtypes: float64(4), int64(4), object(16)
memory usage: 219.3+ KB
None

In [148]:
print(matches.isnull().sum())

match_id              0
season_id             0
balls_per_over        0
city                 51
match_date            0
event_name            0
match_number         70
gender                0
match_type            0
format                0
overs                 0
season                0
team_type             0
venue                 0
toss_winner           1
team1                 0
team2                 0
toss_decision         1
match_winner          8
win_by_runs         638
win_by_wickets      554
player_of_match       8
result                0
stage              1165
dtype: int64

In [149]:
print(deliveries.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 30 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   season_id          278205 non-null  int64
 1   match_id           278205 non-null  int64
 2   batter             278205 non-null  object
 3   bowler             278205 non-null  object
 4   non_striker        278205 non-null  object
 5   team_batting       278205 non-null  object
 6   team_bowling       278205 non-null  object
 7   over_number        278205 non-null  int64
 8   ball_number        278205 non-null  int64
 9   batter_runs        278205 non-null  int64
 10  extras             278205 non-null  int64
 11  total_runs         278205 non-null  int64
 12  batsman_type       278205 non-null  object
 13  bowler_type        278205 non-null  object
 14  player_out         13823 non-null   object
 15  fielders_involved  13823 non-null   object
 16  is_wicket          278205 non-null  bool
 17  is_wide_ball       278205 non-null  bool
 18  is_no_ball         278205 non-null  bool
 19  is_leg_bye         278205 non-null  bool
 20  is_bye             278205 non-null  bool
 21  is_penalty         278205 non-null  bool
 22  wide_ball_runs     278205 non-null  int64
 23  no_ball_runs       278205 non-null  int64
 24  leg_bye_runs       278205 non-null  int64
 25  bye_runs           278205 non-null  int64
 26  penalty_runs       278205 non-null  int64
 27  wicket_kind        13823 non-null   object
 28  is_super_over      278205 non-null  bool
 29  innings            278205 non-null  int64
dtypes: bool(7), int64(13), object(10)
memory usage: 50.7+ MB
None

In [150]:
print(deliveries.isnull().sum())

season_id                 0
match_id                  0
batter                    0
bowler                    0
non_striker               0
team_batting              0
team_bowling              0
over_number               0
ball_number               0
batter_runs               0
extras                    0
total_runs                0
batsman_type              0
bowler_type               0
player_out           264382
fielders_involved    264382
is_wicket                 0
is_wide_ball              0
is_no_ball                0
is_leg_bye                0
is_bye                    0
is_penalty                0
wide_ball_runs            0
no_ball_runs              0
leg_bye_runs              0
bye_runs                  0
penalty_runs              0
wicket_kind          264382
is_super_over             0
innings                   0
dtype: int64

In [151]:
matches.head()

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,toss_winner,team1,team2,toss_decision,match_winner,win_by_runs,win_by_wickets,player_of_match,result,stage
0,335982,2008,6,Bangalore,18-04-2008,Indian Premier League,1.0,male,T20,T20,...,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,field,Kolkata Knight Riders,140.0,NaN,46.0,win,NaN
1,1082591,2017,6,Hyderabad,05-04-2017,Indian Premier League,1.0,male,T20,T20,...,Royal Challengers Bangalore,Sunrisers Hyderabad,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35.0,NaN,15.0,win,NaN
2,1082592,2017,6,Pune,06-04-2017,Indian Premier League,2.0,male,T20,T20,...,Rising Pune Supergiant,Rising Pune Supergiant,Mumbai Indians,field,Rising Pune Supergiant,NaN,7.0,36.0,win,NaN
3,1082593,2017,6,Rajkot,07-04-2017,Indian Premier League,3.0,male,T20,T20,...,Kolkata Knight Riders,Gujarat Lions,Kolkata Knight Riders,field,Kolkata Knight Riders,NaN,10.0,57.0,win,NaN
4,1082594,2017,6,Indore,08-04-2017,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,Punjab Kings,Rising Pune Supergiant,field,Punjab Kings,NaN,6.0,71.0,win,NaN

In [152]:
print(matches.columns)

Index(['match_id', 'season_id', 'balls_per_over', 'city', 'match_date',
       'event_name', 'match_number', 'gender', 'match_type', 'format', 'overs',
       'season', 'team_type', 'venue', 'toss_winner', 'team1', 'team2',
       'toss_decision', 'match_winner', 'win_by_runs', 'win_by_wickets',
       'player_of_match', 'result', 'stage'],
      dtype='object')

In [153]:
deliveries.head()

,season_id,match_id,batter,bowler,non_striker,team_batting,team_bowling,over_number,ball_number,batter_runs,...,is_bye,is_penalty,wide_ball_runs,no_ball_runs,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,Kolkata Knight Riders,Royal Challengers Bangalore,0,0,0,...,False,False,0,0,1,0,0,NaN,False,1
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0,...,False,False,0,0,0,0,0,NaN,False,1
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,...,False,False,1,0,0,0,0,NaN,False,1
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0,...,False,False,0,0,0,0,0,NaN,False,1
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,...,False,False,0,0,0,0,0,NaN,False,1

In [154]:
print(deliveries.columns)

Index(['season_id', 'match_id', 'batter', 'bowler', 'non_striker',
       'team_batting', 'team_bowling', 'over_number', 'ball_number',
       'batter_runs', 'extras', 'total_runs', 'batsman_type', 'bowler_type',
       'player_out', 'fielders_involved', 'is_wicket', 'is_wide_ball',
       'is_no_ball', 'is_leg_bye', 'is_bye', 'is_penalty', 'wide_ball_runs',
       'no_ball_runs', 'leg_bye_runs', 'bye_runs', 'penalty_runs',
       'wicket_kind', 'is_super_over', 'innings'],
      dtype='object')

## Step 4: CLEAN MATCHES TABLE

- HANDLE MISSING VALUES

In [155]:
matches.fillna({'toss_decision': "Unknown"}, inplace=True)
matches.fillna({'toss_winner': "Unknown"}, inplace=True)
matches.fillna({'match_winner': "No Result"}, inplace=True)

- STANDARDIZE TEAM NAMES

In [156]:
def clean_team_name(name):
    if pd.isna(name):
        return name
    name = name.strip().lower()
    
    mapping = {
        'mumbai indians': 'MI',
        'chennai super kings': 'CSK',
        'royal challengers bangalore': 'RCB',
        'kolkata knight riders': 'KKR',
        'delhi capitals': 'DC',
        'sunrisers hyderabad': 'SRH',
        'rajasthan royals': 'RR',
        'punjab kings': 'PBKS',
        'Gujarat Titans': 'GT',
        'Lucknow Super Giants': 'LSG',
        'gujarat titans': 'GT',
        'lucknow super giants': 'LSG',
        'deccan chargers': 'SRH',  # better mapping than DC
        'rising pune supergiant': 'RPS',
        'rising pune supergiants': 'RPS',
        'gujarat lions': 'GL',
        'pune warriors': 'PWI',
        'kochi tuskers kerala': 'KTK',
        'delhi daredevils': 'DC'
    }
    
    return mapping.get(name, name.upper())

matches['team1'] = matches['team1'].apply(clean_team_name)
matches['team2'] = matches['team2'].apply(clean_team_name)
matches['match_winner'] = matches['match_winner'].apply(clean_team_name)
matches['toss_winner'] = matches['toss_winner'].apply(clean_team_name)

- CONVERT DATE PROPERLY

In [157]:
matches['match_date'] = pd.to_datetime(matches['match_date'], errors='coerce')

C:\Users\Harsh Kushwaha\AppData\Local\Temp\ipykernel_19760\2258290704.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  matches['match_date'] = pd.to_datetime(matches['match_date'], errors='coerce')

- REMOVE DUPLICATES

In [158]:
matches.drop_duplicates(inplace=True)

## Step 5: CLEAN DELIVERIES TABLE

- FILL MISSING VALUES

In [159]:
deliveries.fillna({'batter_runs': 0}, inplace=True)
deliveries.fillna({'total_runs': 0}, inplace=True)
deliveries.fillna({'wicket_kind': 0}, inplace=True)

- STANDARDIZE PLAYER NAMES

In [160]:
deliveries['batter'] = deliveries['batter'].str.strip()
deliveries['non_striker'] = deliveries['non_striker'].str.strip()
deliveries['bowler'] = deliveries['bowler'].str.strip()

- REMOVE DUPLICATES

In [161]:
deliveries.drop_duplicates(inplace=True)

- STANDARDIZE TEAM NAMES

In [162]:
def clean_team_name(name):
    if pd.isna(name):
        return name
    name = name.strip().lower()
    
    mapping = {
        'mumbai indians': 'MI',
        'chennai super kings': 'CSK',
        'royal challengers bangalore': 'RCB',
        'kolkata knight riders': 'KKR',
        'delhi capitals': 'DC',
        'sunrisers hyderabad': 'SRH',
        'rajasthan royals': 'RR',
        'punjab kings': 'PBKS',
        'Gujarat Titans': 'GT',
        'Lucknow Super Giants': 'LSG',
        'gujarat titans': 'GT',
        'lucknow super giants': 'LSG',
        'deccan chargers': 'SRH',  # better mapping than DC
        'rising pune supergiant': 'RPS',
        'rising pune supergiants': 'RPS',
        'gujarat lions': 'GL',
        'pune warriors': 'PWI',
        'kochi tuskers kerala': 'KTK',
        'delhi daredevils': 'DC'
    }
    
    return mapping.get(name, name.upper())

deliveries['team_batting'] = deliveries['team_batting'].apply(clean_team_name)
deliveries['team_bowling'] = deliveries['team_bowling'].apply(clean_team_name)

## Step 6: CLEAN PLAYERS TABLE

In [163]:
players.head()

,player_id,player_name,bat_style,bowl_style,field_pos,player_full_name,player_name2,player_image
0,6730,Mohsin Khan,Left hand Bat,Left arm Medium fast,NaN,Mohsin Khan,Mohsin Khan,NaN
1,22,Rashid Khan,Right hand Bat,Legbreak Googly,,Rashid Khan Arman,Rashid Khan,https://www.espncricinfo.com/cricketers/rashid...
2,590,K Rabada,Left hand Bat,Right arm Fast,,Kagiso Rabada,Kagiso Rabada,https://ipl-stats-sports-mechanic.s3.ap-south-...
3,1424,SN Khan,Right hand Bat,Legbreak,,Sarfaraz Naushad Khan,Sarfaraz Naushad,NaN
4,963,MN Samuels,Right hand Bat,Right arm Offbreak,,Marlon Nathaniel Samuels,Marlon Nathaniel,NaN

In [164]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 772 entries, 0 to 771
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         772 non-null    int64
 1   player_name       772 non-null    object
 2   bat_style         772 non-null    object
 3   bowl_style        759 non-null    object
 4   field_pos         707 non-null    object
 5   player_full_name  772 non-null    object
 6   player_name2      772 non-null    object
 7   player_image      134 non-null    object
dtypes: int64(1), object(7)
memory usage: 48.4+ KB

In [165]:
print(matches.isnull().sum())

match_id              0
season_id             0
balls_per_over        0
city                 51
match_date            0
event_name            0
match_number         70
gender                0
match_type            0
format                0
overs                 0
season                0
team_type             0
venue                 0
toss_winner           0
team1                 0
team2                 0
toss_decision         0
match_winner          0
win_by_runs         638
win_by_wickets      554
player_of_match       8
result                0
stage              1165
dtype: int64

- DROP DUPLICATES

In [166]:
players.drop_duplicates(inplace=True)
players['player_name'] = players['player_name'].str.strip()

In [167]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 772 entries, 0 to 771
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         772 non-null    int64
 1   player_name       772 non-null    object
 2   bat_style         772 non-null    object
 3   bowl_style        759 non-null    object
 4   field_pos         707 non-null    object
 5   player_full_name  772 non-null    object
 6   player_name2      772 non-null    object
 7   player_image      134 non-null    object
dtypes: int64(1), object(7)
memory usage: 48.4+ KB

## Step 7: CLEAN TEAM TABLE

In [168]:
teams.head(17)

,team_id,team_name,team_name_short,image_url
0,1,Royal Challengers Bangalore,RCB,https://documents.iplt20.com/ipl/RCB/Logos/Log...
1,2,Sunrisers Hyderabad,SRH,https://documents.iplt20.com/ipl/SRH/Logos/Log...
2,3,Mumbai Indians,MI,https://documents.iplt20.com/ipl/MI/Logos/Logo...
3,4,Rising Pune Supergiant,RPS,https://ipl-stats-sports-mechanic.s3.ap-south-...
4,5,Gujarat Lions,GL,https://ipl-stats-sports-mechanic.s3.ap-south-...
5,6,Kolkata Knight Riders,KKR,https://documents.iplt20.com/ipl/KKR/Logos/Log...
6,129,Chennai Super Kings,CSK,https://documents.iplt20.com/ipl/CSK/logos/Log...
7,134,Rajasthan Royals,RR,https://1000logos.net/wp-content/uploads/2024/...
8,252,Delhi Capitals,DC,https://documents.iplt20.com/ipl/DC/Logos/Logo...
9,494,Punjab Kings,PK,https://documents.iplt20.com/ipl/PBKS/Logos/Lo...
10,614,Lucknow Super Giants,LSG,https://documents.iplt20.com/ipl/LSG/Logos/Log...
11,615,Gujarat Titans,GT,https://documents.iplt20.com/ipl/GT/Logos/Logo...
12,1068,Deccan Chargers,DEC,https://ipl-stats-sports-mechanic.s3.ap-south-...
13,1414,Kochi Tuskers Kerala,KTK,https://ipl-stats-sports-mechanic.s3.ap-south-...
14,1419,Pune Warriors,PWI,https://ipl-stats-sports-mechanic.s3.ap-south-...
15,3604,Rising Pune Supergiants,RPS,https://ipl-stats-sports-mechanic.s3.ap-south-...

In [169]:
teams.drop_duplicates(inplace=True)
teams['team_name'] = teams['team_name'].str.strip().str.upper()

## Step 8: DATA VALIDATION

- CHECK NULL AGAIN

In [170]:
print(matches.isnull().sum())

match_id              0
season_id             0
balls_per_over        0
city                 51
match_date            0
event_name            0
match_number         70
gender                0
match_type            0
format                0
overs                 0
season                0
team_type             0
venue                 0
toss_winner           0
team1                 0
team2                 0
toss_decision         0
match_winner          0
win_by_runs         638
win_by_wickets      554
player_of_match       8
result                0
stage              1165
dtype: int64

In [171]:
print(deliveries.isnull().sum())

season_id                 0
match_id                  0
batter                    0
bowler                    0
non_striker               0
team_batting              0
team_bowling              0
over_number               0
ball_number               0
batter_runs               0
extras                    0
total_runs                0
batsman_type              0
bowler_type               0
player_out           264382
fielders_involved    264382
is_wicket                 0
is_wide_ball              0
is_no_ball                0
is_leg_bye                0
is_bye                    0
is_penalty                0
wide_ball_runs            0
no_ball_runs              0
leg_bye_runs              0
bye_runs                  0
penalty_runs              0
wicket_kind               0
is_super_over             0
innings                   0
dtype: int64

- CHECK UNIQUE TEAMS

In [172]:
print(matches['team1'].unique())

['RCB' 'SRH' 'RPS' 'GL' 'PBKS' 'MI' 'KKR' 'DC' 'RR' 'CSK' 'LSG' 'GT' 'KTK'
 'PWI']

- CHECK BASIC STATISTICS

In [173]:
print(deliveries['total_runs'].describe())

count    278205.00000
mean          1.34535
std           1.63762
min           0.00000
25%           0.00000
50%           1.00000
75%           1.00000
max           7.00000
Name: total_runs, dtype: float64

## FINAL EXPORT (FOR SQL)

In [174]:
matches.to_csv("clean_matches.csv", index=False)
deliveries.to_csv("clean_deliveries.csv", index=False)
players.to_csv("clean_players.csv", index=False)
teams.to_csv("clean_teams.csv", index=False)